kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aspen-mesh-controlplane
  labels:
    app: aspen-mesh-controlplane
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: aspen-mesh-controlplane
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: aspen-mesh-controlplane-view
  apiGroup: rbac.authorization.k8s.io
