apiVersion: v1
description: A Helm chart for managing Aspen Mesh metrics-collector
name: aspen-mesh-metrics-collector
version: 1.4.6-am8
appVersion: 1.4.6-am8
tillerVersion: ">=2.7.2"
keywords:
  - istio
  - aspenmesh
  - metrics
engine: gotpl
icon: https://aspenmesh.io/wp-content/uploads/2018/06/favicon-192.png
