apiVersion: v1
kind: Service
metadata:
  name: aspen-mesh-metrics-collector
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: aspen-mesh-metrics-collector
    chart: {{ template "aspen-mesh-metrics-collector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: aspen-mesh-metrics-collector
  ports:
  - name: http-aspen-mesh-metrics-collector
    port: {{ .Values.server.service.servicePort }}
    protocol: TCP
    targetPort: 9090

{{- if .Values.service.nodePort.enabled }}
# Using separate service for nodeport.
---
apiVersion: v1
kind: Service
metadata:
  name: aspen-mesh-metrics-collector-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: aspen-mesh-metrics-collector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: aspen-mesh-metrics-collector
  ports:
    - name: http
      port: {{ .Values.server.service.servicePort }}
      protocol: TCP
      targetPort: 9090
      nodePort: {{ .Values.service.nodePort.port }}
{{- end }}
